#!/bin/sh -e

echo "-> Copying sources ..."
cp -Rf /tmp/src/. ./

# Check if hugo can compile your site
hugo --baseURL=${HUGO_BASE_URL:-127.0.0.1} --theme ${HUGO_THEME:-learn} \
     --renderToMemory -v && rm -rf public
